import { YamlJsonFormatter } from '@/components/tools/yaml-json-formatter';
import { ToolShell } from '@/components/tools/tool-shell';
import { buildToolMetadata } from '@/lib/tools';

export const metadata = buildToolMetadata('yaml-json-formatter');

function Explainer() {
  return (
    <>
      <h3 className="mb-4 text-xl font-semibold">When to reach for this</h3>
      <ul className="space-y-2 text-sm text-muted-foreground">
        <li>
          <strong className="text-foreground">Debugging Helm values</strong>: paste the rendered template YAML,
          convert to JSON to see the structure clearly.
        </li>
        <li>
          <strong className="text-foreground">Cleaning up an API response</strong>: pretty-print JSON from a
          curl command or paste into YAML for readable diffs.
        </li>
        <li>
          <strong className="text-foreground">Catching syntax errors fast</strong>: the linter surfaces the
          exact position of an unclosed quote or misaligned indent.
        </li>
        <li>
          <strong className="text-foreground">Converting a quick config</strong>: e.g., take a JSON file
          generated by a script and hand it to a YAML-only tool.
        </li>
      </ul>

      <div className="mt-6 rounded-md border border-primary/20 bg-primary/5 p-4">
        <h4 className="mb-2 font-semibold text-sm">About the round-trip</h4>
        <p className="text-sm text-muted-foreground leading-relaxed">
          YAML is a superset of JSON in intent but not 1:1. Multi-document YAML streams
          (<code className="font-mono">---</code> separators) can&apos;t be represented as a single JSON value. Anchors
          and merge keys are resolved during parsing; you won&apos;t see them in the JSON output. Comments are not
          preserved in either direction.
        </p>
      </div>
    </>
  );
}

export default function YamlJsonFormatterPage() {
  return (
    <ToolShell slug="yaml-json-formatter" explainer={<Explainer />}>
      <YamlJsonFormatter />
    </ToolShell>
  );
}
