// Auto-generated blur placeholder data for images
// This file is generated by scripts/generate-blur-placeholders.ts

export interface BlurDataMap {
  [imagePath: string]: string; // base64 blur placeholder
}

let cachedBlurData: BlurDataMap | null = null;

export function getBlurPlaceholder(imagePath: string): string | undefined {
  if (!cachedBlurData) {
    try {
      // In production/build, this will be bundled
      // In development, it will be read from the cache file
      cachedBlurData = {} as BlurDataMap;
    } catch {
      cachedBlurData = {};
    }
  }

  return cachedBlurData[imagePath];
}

// Generates a shimmer SVG placeholder as fallback
export function getShimmerPlaceholder(width: number = 400, height: number = 300): string {
  const shimmer = (w: number, h: number) => `
    <svg width="${w}" height="${h}" version="1.1" xmlns="http://www.w3.org/2000/svg">
      <defs>
        <linearGradient id="g">
          <stop stop-color="#f6f7f8" offset="0%" />
          <stop stop-color="#edeef1" offset="20%" />
          <stop stop-color="#f6f7f8" offset="40%" />
          <stop stop-color="#f6f7f8" offset="100%" />
        </linearGradient>
      </defs>
      <rect width="${w}" height="${h}" fill="#f6f7f8" />
      <rect id="r" width="${w}" height="${h}" fill="url(#g)" />
      <animate xlink:href="#r" attributeName="x" from="-${w}" to="${w}" dur="1s" repeatCount="indefinite"  />
    </svg>
  `;

  const toBase64 = (str: string) =>
    typeof window === 'undefined' ? Buffer.from(str).toString('base64') : window.btoa(str);

  return `data:image/svg+xml;base64,${toBase64(shimmer(width, height))}`;
}
