// lib/games.ts
export interface Game {
  id: string;
  title: string;
  /**
   * Optional longer title used only for the <title> tag and OG/Twitter
   * cards. SEO tools flag titles under ~30 chars; some games (Bug Hunter,
   * BCDR Simulator) have short display titles that read fine on cards
   * but are too short on their own as page titles. Set this when the
   * display title needs more context for search engines and social
   * previews.
   */
  seoTitle?: string;
  description: string;
  iconName: string;
  badgeText?: string;
  color: string;
  href: string;
  tags: string[];
  isNew?: boolean;
  isHot?: boolean;
  isPopular?: boolean;
  isComingSoon?: boolean;
  featured?: boolean;
  category?: string;
  type?: 'game' | 'simulator';
  createdAt?: string; // ISO 8601 date string for sorting
}

/**
 * Games configuration
 * This is the single source of truth for game metadata
 */
const games: Game[] = [
  {
    id: 'sql-terminal-simulator',
    type: 'simulator',
    title: 'SQL Terminal Simulator',
    seoTitle: 'SQL Terminal Simulator: Practice SQL Queries in the Browser',
    description:
      'Practice SQL in an interactive browser terminal. Learn SELECT, WHERE, ORDER BY, DISTINCT, aggregates, GROUP BY, HAVING, JOINs, subqueries, and window functions against a small e-commerce schema, with single-table queries evaluated live and verified Postgres output.',
    iconName: 'Database',
    badgeText: 'New',
    color: 'from-sky-500 to-indigo-600',
    href: '/games/sql-terminal-simulator',
    tags: [
      'sql',
      'postgres',
      'postgresql',
      'database',
      'queries',
      'select',
      'joins',
      'aggregates',
      'terminal',
      'backend',
      'educational',
      'interactive',
    ],
    isNew: true,
    featured: true,
    category: 'Database',
    createdAt: '2026-07-03',
  },
  {
    id: 'postgres-terminal-simulator',
    type: 'simulator',
    title: 'PostgreSQL Terminal Simulator',
    seoTitle: 'PostgreSQL psql Simulator: EXPLAIN, Indexes, Transactions',
    description:
      'Practice the psql tool and Postgres engine in an interactive browser terminal. Explore with meta-commands, read real EXPLAIN plans, add an index to turn a sequential scan into a bitmap index scan, and use BEGIN and ROLLBACK to make changes safe, all against a small e-commerce database with verified PostgreSQL output.',
    iconName: 'Database',
    badgeText: 'New',
    color: 'from-blue-600 to-slate-700',
    href: '/games/postgres-terminal-simulator',
    tags: [
      'postgresql',
      'psql',
      'database',
      'explain',
      'indexes',
      'transactions',
      'sql',
      'educational',
      'interactive',
    ],
    isNew: true,
    featured: true,
    category: 'Database',
    createdAt: '2026-07-03',
  },
  {
    id: 'mongodb-terminal-simulator',
    type: 'simulator',
    title: 'MongoDB Terminal Simulator',
    seoTitle: 'MongoDB Query Simulator: find, Operators, and Aggregation',
    description:
      'Practice MongoDB queries in an interactive browser terminal. Learn find and projections, query operators like $lt, $gt, and $in, sort, skip, limit, countDocuments, insert, update, delete, and the aggregation pipeline with $match, $group, and $sort, against a small e-commerce dataset that runs live in your browser.',
    iconName: 'Database',
    badgeText: 'New',
    color: 'from-emerald-500 to-green-700',
    href: '/games/mongodb-terminal-simulator',
    tags: [
      'mongodb',
      'nosql',
      'mongo',
      'database',
      'documents',
      'find',
      'aggregation',
      'queries',
      'terminal',
      'backend',
      'educational',
      'interactive',
    ],
    isNew: true,
    featured: true,
    category: 'Database',
    createdAt: '2026-07-07',
  },
  {
    id: 'fork-bomb-simulator',
    type: 'simulator',
    title: 'Fork Bomb Simulator',
    description:
      'Visualize how the infamous :(){ :|:& };: fork bomb works. Watch processes multiply exponentially, exhaust system resources, and learn how to protect against it with ulimit, cgroups, and systemd.',
    iconName: 'Zap',
    badgeText: 'New',
    color: 'from-red-500 to-orange-600',
    href: '/games/fork-bomb-simulator',
    tags: ['linux', 'bash', 'security', 'processes', 'educational', 'interactive'],
    isNew: true,
    featured: true,
    category: 'Security',
    createdAt: '2026-04-03',
  },
  {
    id: 'aws-vpc-simulator',
    type: 'simulator',
    title: 'AWS VPC Networking Simulator',
    description:
      'Learn AWS networking fundamentals with an interactive VPC simulator. Visualize how traffic flows through public and private subnets, understand NAT Gateways, Internet Gateways, and route tables.',
    iconName: 'Cloud',
    badgeText: 'New',
    color: 'from-orange-500 to-yellow-600',
    href: '/games/aws-vpc-simulator',
    tags: ['aws', 'vpc', 'networking', 'cloud', 'educational', 'interactive', 'infrastructure'],
    isNew: true,
    category: 'Cloud',
    createdAt: '2026-02-07',
  },
  {
    id: 'dns-simulator',
    type: 'simulator',
    title: 'DNS Resolution Simulator',
    description:
      'Learn how DNS works with an interactive step-by-step simulator. Visualize the DNS hierarchy, understand caching at different levels, and see the difference between recursive and iterative queries.',
    iconName: 'Globe',
    badgeText: 'New',
    color: 'from-blue-500 to-cyan-600',
    href: '/games/dns-simulator',
    tags: ['dns', 'networking', 'educational', 'interactive', 'infrastructure'],
    isNew: true,
    featured: true,
    category: 'Networking',
    createdAt: '2026-02-07',
  },
  {
    id: 'db-indexing-simulator',
    type: 'simulator',
    title: 'Database Indexing Simulator',
    description:
      'Learn how database indexes work with an interactive simulator. See the difference between full table scans and index seeks, understand B-tree structure, and learn when to create indexes.',
    iconName: 'Table',
    badgeText: 'New',
    color: 'from-emerald-500 to-teal-600',
    href: '/games/db-indexing-simulator',
    tags: ['database', 'sql', 'performance', 'indexing', 'educational', 'backend'],
    isNew: true,
    featured: true,
    category: 'Database',
    createdAt: '2026-02-07',
  },
  {
    id: 'database-replication-sharding-scaling',
    type: 'simulator',
    title: 'Database Replication, Sharding & Scaling',
    seoTitle: 'Database Replication, Sharding and Scaling Simulator',
    description:
      'Explore database replication, sharding, and scaling with an interactive simulator. Compare sync vs async replication, shard key choices, hot spots, failover behavior, read replicas, write scaling, connection pooling, cost, and latency.',
    iconName: 'Database',
    badgeText: 'New',
    color: 'from-primary to-primary/60',
    href: '/games/database-replication-sharding-scaling',
    tags: [
      'database',
      'replication',
      'sharding',
      'scaling',
      'distributed-systems',
      'postgresql',
      'architecture',
      'educational',
      'interactive',
    ],
    isNew: true,
    featured: true,
    category: 'Database',
    createdAt: '2026-05-14',
  },
  {
    id: 'postgres-wire-protocol',
    type: 'simulator',
    title: 'PostgreSQL Wire Protocol Simulator',
    seoTitle: 'PostgreSQL Wire Protocol Simulator: Visualize Frontend Backend Messages',
    description:
      'Visualize the PostgreSQL wire protocol with an interactive simulator. Step through TLS negotiation, StartupMessage, SCRAM authentication, simple queries, extended queries, RowDescription, DataRow streams, ErrorResponse, COPY, and ReadyForQuery.',
    iconName: 'Database',
    badgeText: 'New',
    color: 'from-sky-500 to-emerald-600',
    href: '/games/postgres-wire-protocol',
    tags: [
      'postgresql',
      'postgres',
      'database',
      'wire-protocol',
      'networking',
      'sql',
      'backend',
      'educational',
      'interactive',
    ],
    isNew: true,
    featured: true,
    category: 'Database',
    createdAt: '2026-05-22',
  },
  {
    id: 'docker-terminal-simulator',
    type: 'simulator',
    title: 'Docker Terminal Simulator',
    seoTitle: 'Docker Terminal Simulator: Practice Docker Commands in the Browser',
    description:
      'Practice Docker commands in an interactive browser terminal. Learn images, containers, logs, exec, Dockerfile builds, volumes, networks, and Docker Compose with a live Docker daemon visualization.',
    iconName: 'Boxes',
    badgeText: 'New',
    color: 'from-sky-500 to-blue-700',
    href: '/games/docker-terminal-simulator',
    tags: [
      'docker',
      'containers',
      'terminal',
      'devops',
      'compose',
      'networking',
      'volumes',
      'educational',
      'interactive',
    ],
    isNew: true,
    featured: true,
    category: 'DevOps',
    createdAt: '2026-05-28',
  },
  {
    id: 'kubernetes-terminal-simulator',
    type: 'simulator',
    title: 'Kubernetes Terminal Simulator',
    seoTitle: 'Kubernetes Terminal Simulator: Practice kubectl in the Browser',
    description:
      'Practice Kubernetes commands in an interactive browser terminal. Learn kubectl contexts, nodes, Pods, Deployments, Services, rollouts, logs, exec, events, ConfigMaps, and cleanup workflows with a live cluster visualization.',
    iconName: 'Boxes',
    badgeText: 'New',
    color: 'from-primary to-sky-600',
    href: '/games/kubernetes-terminal-simulator',
    tags: [
      'kubernetes',
      'kubectl',
      'containers',
      'terminal',
      'pods',
      'deployments',
      'services',
      'rollouts',
      'devops',
      'educational',
      'interactive',
    ],
    isNew: true,
    featured: true,
    category: 'DevOps',
    createdAt: '2026-06-01',
  },
  {
    id: 'terraform-terminal-simulator',
    type: 'simulator',
    title: 'Terraform Basics Simulator',
    seoTitle: 'Terraform Basics: Learn init, plan, apply, and destroy (Interactive Lab)',
    description:
      'Learn Terraform basics in an interactive browser lab. Read and edit the HCL config, run init, validate, plan, apply, and destroy, and watch state react to your edits. A free, hands-on way to learn infrastructure as code with no AWS account.',
    iconName: 'Cloud',
    badgeText: 'New',
    color: 'from-violet-500 to-purple-700',
    href: '/games/terraform-terminal-simulator',
    tags: [
      'terraform',
      'learn-terraform',
      'terraform-basics',
      'terraform-tutorial',
      'iac',
      'infrastructure-as-code',
      'hcl',
      'aws',
      'terminal',
      'devops',
      'beginner',
      'educational',
      'interactive',
    ],
    isNew: true,
    featured: true,
    category: 'DevOps',
    createdAt: '2026-06-07',
  },
  {
    id: 'latency-percentiles-simulator',
    type: 'simulator',
    title: 'P90, P95 & P99 Latency Simulator',
    seoTitle: 'P90, P95 and P99 Latency Simulator: Understand Percentile Metrics',
    description:
      'Learn latency percentiles with an interactive simulator. Generate request samples, visualize distributions, compare average latency with P50, P90, P95, and P99, and see how tail latency affects real users.',
    iconName: 'LineChart',
    badgeText: 'New',
    color: 'from-cyan-500 to-emerald-600',
    href: '/games/latency-percentiles-simulator',
    tags: [
      'latency',
      'percentiles',
      'p90',
      'p95',
      'p99',
      'monitoring',
      'observability',
      'sre',
      'performance',
      'slo',
      'educational',
      'interactive',
    ],
    isNew: true,
    featured: true,
    category: 'Monitoring',
    createdAt: '2026-06-05',
  },
  {
    id: 'kubernetes-networking-cni-simulator',
    type: 'simulator',
    title: 'Kubernetes Networking / CNI Simulator',
    seoTitle: 'Kubernetes Networking and CNI Simulator: Visualize Pod, Service and Ingress Traffic',
    description:
      'Visualize Kubernetes networking and CNI packet paths with an interactive simulator. Learn Pod-to-Pod routing, same-node and cross-node traffic, ClusterIP Services, EndpointSlices, headless Services, LoadBalancer, NodePort, kube-proxy, eBPF service routing, Ingress, NetworkPolicy, and internet egress.',
    iconName: 'Network',
    badgeText: 'New',
    color: 'from-primary to-cyan-600',
    href: '/games/kubernetes-networking-cni-simulator',
    tags: [
      'kubernetes',
      'cni',
      'networking',
      'pods',
      'services',
      'clusterip',
      'endpointslice',
      'headless-service',
      'loadbalancer',
      'nodeport',
      'ingress',
      'networkpolicy',
      'kube-proxy',
      'ebpf',
      'devops',
      'educational',
      'interactive',
    ],
    isNew: true,
    featured: true,
    category: 'Networking',
    createdAt: '2026-06-02',
  },
  {
    id: 'git-concepts-simulator',
    type: 'simulator',
    title: 'Git Concepts Simulator',
    seoTitle: 'Git Concepts Simulator: Learn Branches, Commits, Staging and Remotes',
    description:
      'Practice Git in an interactive browser terminal with a visual repository model. Learn the working directory, staging area, local commits, branch pointers, remotes, fast-forward merges, fetch, and rebase.',
    iconName: 'GitBranch',
    badgeText: 'New',
    color: 'from-primary to-orange-600',
    href: '/games/git-concepts-simulator',
    tags: [
      'git',
      'version-control',
      'terminal',
      'branches',
      'commits',
      'merge',
      'rebase',
      'devops',
      'educational',
      'interactive',
    ],
    isNew: true,
    featured: true,
    category: 'DevOps',
    createdAt: '2026-06-01',
  },
  {
    id: 'javascript-promises-async-await-simulator',
    type: 'simulator',
    title: 'JavaScript Promises & Async/Await Simulator',
    seoTitle: 'JavaScript Promises and Async/Await Simulator: Visualize Microtasks and the Event Loop',
    description:
      'Visualize JavaScript promises, async/await, microtasks, task queues, setTimeout ordering, rejection handling, and Promise.all with an interactive event-loop simulator inspired by classic JavaScript visual guides.',
    iconName: 'Braces',
    badgeText: 'New',
    color: 'from-primary to-yellow-600',
    href: '/games/javascript-promises-async-await-simulator',
    tags: [
      'javascript',
      'promises',
      'async-await',
      'event-loop',
      'microtasks',
      'settimeout',
      'nodejs',
      'programming',
      'frontend',
      'backend',
      'educational',
      'interactive',
    ],
    isNew: true,
    featured: true,
    category: 'Programming',
    createdAt: '2026-06-03',
  },
  {
    id: 'oauth-oidc-flow-simulator',
    type: 'simulator',
    title: 'OAuth/OIDC Flow Simulator',
    seoTitle: 'OAuth/OIDC Flow Simulator: Visualize Auth Code, PKCE and Tokens',
    description:
      'Visualize OAuth 2.0 and OpenID Connect flows with an interactive simulator. Learn authorization code + PKCE, state, nonce, redirect URI checks, ID tokens, access tokens, refresh tokens, scopes, UserInfo, and common auth failure modes.',
    iconName: 'Shield',
    badgeText: 'New',
    color: 'from-primary to-emerald-600',
    href: '/games/oauth-oidc-flow-simulator',
    tags: [
      'oauth',
      'oidc',
      'openid-connect',
      'authentication',
      'authorization',
      'pkce',
      'jwt',
      'tokens',
      'security',
      'educational',
      'interactive',
    ],
    isNew: true,
    featured: true,
    category: 'Security',
    createdAt: '2026-06-01',
  },
  {
    id: 'smtp-flow-simulator',
    type: 'simulator',
    title: 'SMTP Flow Simulator',
    seoTitle: 'SMTP Flow Simulator: Visualize Email Delivery, Auth, Retries and Bounces',
    description:
      'Visualize how SMTP email delivery works from app submission through EHLO, STARTTLS, AUTH, MAIL FROM, RCPT TO, DATA, SPF, DKIM, DMARC, recipient MX relay, retries, bounces, and inbox placement. Sponsored by SMTPfast.',
    iconName: 'Mail',
    badgeText: 'New',
    color: 'from-primary to-blue-600',
    href: '/games/smtp-flow-simulator',
    tags: [
      'smtp',
      'email',
      'deliverability',
      'spf',
      'dkim',
      'dmarc',
      'dns',
      'networking',
      'educational',
      'interactive',
    ],
    isNew: true,
    featured: true,
    category: 'Networking',
    createdAt: '2026-05-28',
  },
  {
    id: 'message-queue-simulator',
    type: 'simulator',
    title: 'Message Queue Simulator',
    seoTitle: 'Message Queue Simulator: Visualize Kafka and RabbitMQ Queues',
    description:
      'Visualize how message queues work across Kafka and RabbitMQ patterns. Explore producers, brokers, topics, partitions, exchanges, queues, consumer groups, lag, rebalancing, backpressure, ordering, and dead letter queues.',
    iconName: 'MessageSquare',
    badgeText: 'New',
    color: 'from-primary to-sky-600',
    href: '/games/message-queue-simulator',
    tags: [
      'message-queue',
      'kafka',
      'rabbitmq',
      'queues',
      'streaming',
      'backend',
      'infrastructure',
      'distributed-systems',
      'educational',
      'interactive',
    ],
    isNew: true,
    featured: true,
    category: 'Infrastructure',
    createdAt: '2026-05-31',
  },
  {
    id: 'caching-simulator',
    type: 'simulator',
   title: 'Caching Strategies Simulator',
   description:
     'Learn caching fundamentals with an interactive simulator. Visualize cache hits, misses, eviction policies (LRU, LFU, FIFO), and understand write strategies.',
   iconName: 'Database',
   badgeText: 'New',
   color: 'from-purple-500 to-pink-600',
   href: '/games/caching-simulator',
   tags: ['caching', 'performance', 'redis', 'educational', 'interactive', 'backend'],
   isNew: true,
   category: 'Infrastructure',
   createdAt: '2026-02-07',
  },
  {
    id: 'deployment-strategies',
    type: 'simulator',
   title: 'Deployment Strategies Simulator',
   description:
     'Learn deployment strategies like Blue-Green, Canary, Rolling Updates, and Recreate. Visualize how each strategy handles traffic routing, downtime, and rollbacks.',
   iconName: 'Rocket',
   badgeText: 'New',
   color: 'from-indigo-500 to-blue-600',
   href: '/games/deployment-strategies',
   tags: ['deployment', 'kubernetes', 'devops', 'educational', 'interactive', 'ci-cd'],
   isNew: true,
   category: 'DevOps',
   createdAt: '2026-01-31',
  },
  {
    id: 'rest-vs-graphql',
    type: 'simulator',
   title: 'REST API vs GraphQL Simulator',
   description:
     'Compare REST and GraphQL side-by-side. Understand over-fetching, under-fetching, the N+1 problem, and when to use each approach with interactive scenarios.',
   iconName: 'FileJson',
   badgeText: 'New',
   color: 'from-orange-500 to-pink-600',
   href: '/games/rest-vs-graphql',
   tags: ['api', 'rest', 'graphql', 'educational', 'interactive', 'backend'],
   isNew: true,
   category: 'API Design',
   createdAt: '2026-02-01',
  },
  {
    id: 'scaling-simulator',
    type: 'simulator',
   title: 'Horizontal vs Vertical Scaling Simulator',
   description:
     'Interactive game to learn scaling strategies for web applications. Experiment with horizontal and vertical scaling, see the effects on performance, cost, and reliability with realistic pricing simulation and budget constraints.',
   iconName: 'TrendingUp',
   badgeText: 'New',
   color: 'from-emerald-500 to-teal-600',
   href: '/games/scaling-simulator',
   tags: ['scaling', 'infrastructure', 'educational', 'interactive', 'cloud', 'auto-scaling'],
   isNew: true,
   featured: true,
   category: 'Infrastructure',
   createdAt: '2026-01-17',
  },
  {
    id: 'bcdr-simulator',
    type: 'simulator',
    title: 'BCDR Simulator',
    seoTitle: 'BCDR Simulator: Interactive Disaster Recovery Planning',
    description:
      'Learn Business Continuity & Disaster Recovery with interactive RTO/RPO planning, failover strategies, and disaster scenarios. Understand hot, warm, and cold DR sites.',
    iconName: 'Shield',
    badgeText: 'New',
    color: 'from-red-500 to-orange-600',
    href: '/games/bcdr-simulator',
    tags: ['bcdr', 'disaster-recovery', 'infrastructure', 'educational', 'devops'],
    isNew: true,
    category: 'Infrastructure',
    createdAt: '2026-02-14',
  },
  {
    id: 'ssl-tls-handshake',
    type: 'simulator',
    title: 'SSL/TLS Handshake Simulator',
    description:
      'Visualize how SSL/TLS handshakes work with certificate verification, key exchange, and cipher negotiation. Compare TLS 1.2 and 1.3 protocols.',
    iconName: 'Lock',
    badgeText: 'New',
    color: 'from-green-500 to-emerald-600',
    href: '/games/ssl-tls-handshake',
    tags: ['security', 'networking', 'tls', 'ssl', 'certificates', 'educational'],
    isNew: true,
    category: 'Security',
    createdAt: '2026-02-15',
  },
  {
    id: 'linux-terminal',
    type: 'game',
    title: 'Learn Linux - Interactive Tutorial',
    description:
      'Master essential Linux commands through interactive lessons. Practice pwd, ls, cd, cat, grep, chmod, pipes, and more in a simulated terminal environment with 6 progressive lessons.',
    iconName: 'Terminal',
    badgeText: 'New',
    color: 'from-gray-700 to-gray-900',
    href: '/games/linux-terminal',
    tags: ['linux', 'terminal', 'educational', 'interactive', 'tutorial', 'beginner'],
    isNew: true,
    category: 'Educational',
    createdAt: '2026-01-18',
  },
  {
    id: 'load-balancer-simulator',
    type: 'simulator',
   title: 'Load Balancer Algorithm Simulator',
   description:
     'Learn how different load balancing algorithms distribute traffic across servers. Experiment with Round Robin, Least Connections, IP Hash, and more. See how load balancers handle failures and optimize performance.',
   iconName: 'Server',
   badgeText: 'New',
   color: 'from-cyan-500 to-blue-600',
   href: '/games/load-balancer-simulator',
   tags: ['load-balancing', 'networking', 'educational', 'interactive', 'infrastructure'],
   isNew: true,
   featured: true,
   category: 'Infrastructure',
   createdAt: '2026-01-11',
  },
  {
    id: 'dbms-simulator',
    type: 'simulator',
    title: 'Database Management Systems',
    description:
      'Learn about different database types (SQL, NoSQL, Graph, Time-Series) and their use cases. Explore CAP theorem trade-offs and make informed database choices.',
    iconName: 'Database',
    badgeText: 'New',
    color: 'from-blue-500 to-cyan-600',
    href: '/games/dbms-simulator',
    tags: ['database', 'sql', 'nosql', 'educational', 'interactive'],
    isNew: true,
    category: 'Infrastructure',
    createdAt: '2025-12-28',
  },
  {
    id: 'gitops-workflow',
    type: 'simulator',
    title: 'GitOps Workflow Simulator',
    description:
      'Learn GitOps principles through interactive scenarios. Understand Git as source of truth, automated sync, and drift detection.',
    iconName: 'GitBranch',
    badgeText: 'New',
    color: 'from-indigo-500 to-purple-600',
    href: '/games/gitops-workflow',
    tags: ['gitops', 'kubernetes', 'argocd', 'educational', 'interactive'],
    isNew: true,
    category: 'DevOps',
    createdAt: '2025-12-28',
  },
  {
    id: 'bug-hunter',
    type: 'game',
    title: 'Bug Hunter',
    seoTitle: 'Bug Hunter: Snake-Style DevOps Game in the Browser',
    description:
      'DevOps-themed Snake game where you control a bug that infects healthy servers. Grow longer with each infection, but avoid crashing into walls or yourself!',
    iconName: 'Bug',
    badgeText: 'New',
    color: 'from-red-500 to-orange-600',
    href: '/games/bug-hunter',
    tags: ['game', 'arcade', 'interactive', 'security'],
    isNew: true,
    category: 'Games',
    createdAt: '2025-12-07',
  },
  {
    id: 'tcp-vs-udp',
    type: 'simulator',
   title: 'TCP vs UDP Simulator',
   description:
     'Interactive visualization showing the differences between TCP\'s reliable connection-oriented protocol and UDP\'s fast connectionless approach. See the 3-way handshake, packet loss, and retransmissions in action.',
   iconName: 'Network',
   badgeText: 'New',
   color: 'from-cyan-500 to-green-600',
   href: '/games/tcp-vs-udp',
   tags: ['networking', 'educational', 'interactive', 'protocols'],
   isNew: true,
   featured: true,
   category: 'Networking',
   createdAt: '2025-11-25',
  },
  {
    id: 'devops-scorecard',
    type: 'game',
    title: 'DevOps Scorecard',
    description:
      'Evaluate your DevOps skills across 8 key areas and generate a beautiful, shareable scorecard with personalized insights.',
    iconName: 'Trophy',
    badgeText: 'New',
    color: 'from-blue-500 to-purple-600',
    href: '/games/devops-scorecard',
    tags: ['assessment', 'career', 'skills'],
    isNew: true,
    category: 'Assessment',
    createdAt: '2025-11-23',
  },
  {
    id: 'microservices-simulator',
    type: 'simulator',
    title: 'Microservices Architecture Simulator',
    description:
      'Design and deploy microservices. See communication patterns, handle failures, and scale independently. Learn when to use microservices and understand the trade-offs.',
    iconName: 'Boxes',
    badgeText: 'New',
    color: 'from-purple-500 to-pink-600',
    href: '/games/microservices-simulator',
    tags: ['microservices', 'architecture', 'interactive', 'distributed-systems'],
    isNew: true,
    category: 'Architecture',
    createdAt: '2025-12-27',
  },
  {
    id: 'k8s-scheduler',
    type: 'simulator',
   title: 'Kubernetes Scheduler Challenge',
   description:
     'Drag-and-drop Pods onto Nodes while honoring kube scheduling rules: resources, taints/tolerations, selectors, and topology spread.',
   iconName: 'LineChart',
   color: 'from-sky-500 to-cyan-600',
   href: '/games/k8s-scheduler',
   tags: ['kubernetes', 'scheduling', 'interactive'],
   category: 'Kubernetes',
   createdAt: '2025-11-23',
  },
  {
    id: 'rate-limit-simulator',
    type: 'simulator',
    title: 'Rate Limit Simulator',
    description:
      'Learn API rate limiting, backoff strategies, and throttling with real-time visualization and interactive charts.',
    iconName: 'Activity',
    badgeText: 'Popular',
    color: 'from-blue-500 to-cyan-600',
    href: '/games/rate-limit-simulator',
    tags: ['educational', 'API', 'interactive'],
    isPopular: true,
    category: 'APIs',
    createdAt: '2025-11-23',
  },
  {
    id: 'ddos-simulator',
    type: 'simulator',
   title: 'DDoS Attack Simulator',
   description:
     'Educational simulator to understand how DDoS attacks work with stunning real-time visualizations, multiple attack vectors, and protection mechanisms.',
   iconName: 'Shield',
   color: 'from-red-500 to-orange-600',
   href: '/games/ddos-simulator',
   tags: ['educational', 'security', 'interactive', 'visualization'],
   featured: true,
   category: 'Security',
   createdAt: '2025-11-23',
  },
  {
    id: 'scalable-sentry',
    type: 'game',
    title: 'Scalable Sentry',
    description:
      'Tower defense game where you defend your infrastructure against waves of network traffic. Deploy servers, manage resources, and survive boss waves!',
    iconName: 'Shield',
    badgeText: 'New',
    color: 'from-indigo-500 to-purple-600',
    href: '/games/scalable-sentry',
    tags: ['game', 'tower-defense', 'strategy', 'networking'],
    isNew: true,
    category: 'Games',
    createdAt: '2025-11-23',
  },
  {
    id: 'packet-journey',
    type: 'simulator',
    title: 'Network Packet Journey',
    description:
      'Follow a single HTTP/HTTPS packet through the entire network stack with stunning animations. Learn DNS, TCP, TLS, CDN, load balancing, and more!',
    iconName: 'Network',
    badgeText: 'New',
    color: 'from-cyan-500 to-blue-600',
    href: '/games/packet-journey',
    tags: ['educational', 'networking', 'interactive', 'visualization'],
    isNew: true,
    category: 'Networking',
    createdAt: '2025-11-23',
  },
  {
    id: 'cicd-stack-generator',
    type: 'game',
    title: 'CI/CD Stack Generator',
    description: 'Spin the reels to generate your perfect (or perfectly cursed) DevOps stack!',
    iconName: 'Workflow',
    badgeText: 'Fun',
    color: 'from-emerald-500 to-blue-600',
    href: '/games/cicd-stack-generator',
    tags: ['fun', 'interactive'],
    isHot: true,
    category: 'CI/CD',
    createdAt: '2025-11-23',
  },
  {
    id: 'infra-tarot',
    type: 'game',
    title: 'Infra Tarot Cards',
    description:
      'Draw mystical cards to discover your infrastructure destiny! Get humorous readings about your DevOps future.',
    iconName: 'Sparkles',
    color: 'from-purple-500 to-blue-600',
    href: '/games/infra-tarot',
    tags: ['fun', 'humor', 'mystical'],
    featured: false,
    category: 'Fun',
    createdAt: '2025-11-23',
  },
  {
    id: 'devops-memes',
    type: 'game',
    title: 'You Might Be a DevOps Engineer If...',
    description:
      'Auto-generating hilarious and painfully accurate DevOps memes. Each reload brings a new dose of reality!',
    iconName: 'Laugh',
    badgeText: 'Hot',
    color: 'from-orange-500 to-red-600',
    href: '/games/devops-memes',
    tags: ['humor', 'memes', 'viral'],
    isHot: true,
    category: 'Fun',
    createdAt: '2025-11-23',
  },
  {
    id: 'cards-against-devops',
    type: 'game',
    title: 'Cards Against DevOps',
    description:
      'A hilariously inappropriate DevOps party game. Fill in the blanks with the most outrageous DevOps scenarios!',
    iconName: 'Heart',
    color: 'from-pink-500 to-red-600',
    href: '/games/cards-against-devops',
    tags: ['humor', 'party', 'interactive'],
    category: 'Fun',
    createdAt: '2025-11-23',
  },
  {
    id: 'git-quiz',
    type: 'game',
    title: 'Git Command Quiz',
    description: 'Test your Git knowledge with interactive scenarios covering branches, merges, rebases, conflicts, and the recovery commands you reach for under pressure.',
    iconName: 'Activity',
    badgeText: 'Popular',
    color: 'from-orange-500 to-amber-600',
    href: '/games/git-quiz',
    tags: ['git', 'quiz', 'interactive'],
    isPopular: true,
    category: 'Git',
    createdAt: '2025-11-23',
  },
  {
    id: 'uptime-defender',
    type: 'game',
    title: 'Uptime Defender',
    description:
      'Fast-paced SRE game where you defend your infrastructure uptime! Handle incoming incidents by adding nodes, rotating logs, failing over, restarting pods, and scaling databases.',
    iconName: 'Server',
    badgeText: 'New',
    color: 'from-green-500 to-emerald-600',
    href: '/games/uptime-defender',
    tags: ['game', 'sre', 'interactive', 'real-time'],
    isNew: true,
    category: 'SRE',
    createdAt: '2025-11-23',
  },
  {
    id: 'incident-commander',
    type: 'simulator',
    title: 'Incident Commander Simulator',
    description: 'Lead your team through production incidents and learn incident management best practices.',
    iconName: 'Zap',
    badgeText: 'Coming Soon',
    color: 'from-purple-500 to-indigo-600',
    href: '#',
    tags: ['incident-management', 'sre', 'leadership'],
    isComingSoon: true,
    category: 'SRE',
  },
  {
    id: 'terraform-puzzle',
    type: 'simulator',
    title: 'Terraform State Puzzle',
    description: 'Fix complex Terraform state issues and learn advanced IaC troubleshooting techniques.',
    iconName: 'Shield',
    badgeText: 'Coming Soon',
    color: 'from-green-500 to-teal-600',
    href: '#',
    tags: ['terraform', 'infrastructure', 'troubleshooting'],
    isComingSoon: true,
    category: 'Infrastructure as Code',
  },
  {
    id: 'database-performance',
    type: 'simulator',
    title: 'Database Performance Tuning',
    description: 'Optimize slow queries and database configurations in real-world scenarios.',
    iconName: 'Database',
    badgeText: 'Coming Soon',
    color: 'from-blue-500 to-indigo-600',
    href: '#',
    tags: ['database', 'performance', 'sql'],
    isComingSoon: true,
    category: 'Databases',
  },
  {
    id: 'cloud-cost-optimizer',
    type: 'simulator',
    title: 'Cloud Cost Optimizer Game',
    description: 'Make architectural decisions to reduce cloud costs while maintaining performance and reliability.',
    iconName: 'Cloud',
    badgeText: 'Coming Soon',
    color: 'from-emerald-500 to-green-600',
    href: '#',
    tags: ['cloud', 'cost-optimization', 'architecture'],
    isComingSoon: true,
    category: 'Cloud',
  },
  {
    id: 'docker-escape',
    type: 'simulator',
    title: 'Container Security Challenge',
    description: 'Learn container security by identifying and fixing vulnerabilities in Docker configurations.',
    iconName: 'Shield',
    badgeText: 'Coming Soon',
    color: 'from-red-500 to-pink-600',
    href: '#',
    tags: ['security', 'docker', 'containers'],
    isComingSoon: true,
    category: 'Security',
  },
  {
    id: 'promql-playground',
    type: 'simulator',
    title: 'Prometheus Query Builder (PromQL Playground)',
    description:
      'Learn Prometheus Query Language (PromQL) with an interactive playground. Master label filtering, rate calculations, aggregations, and histogram quantiles with real-time query execution.',
    iconName: 'ActivitySquare',
    badgeText: 'New',
    color: 'from-orange-500 to-red-600',
    href: '/games/promql-playground',
    tags: ['prometheus', 'promql', 'observability', 'sre', 'metrics', 'monitoring'],
    isNew: true,
    featured: true,
    category: 'Observability',
    createdAt: '2026-02-08',
  },
  {
    id: 'service-mesh-simulator',
    type: 'simulator',
    title: 'Service Mesh Traffic Simulator',
    description:
      'Visualize how service mesh proxies handle traffic between microservices. Learn mTLS, traffic splitting, retries, circuit breakers, and explore Istio and Linkerd patterns.',
    iconName: 'Network',
    badgeText: 'New',
    color: 'from-blue-500 to-purple-600',
    href: '/games/service-mesh-simulator',
    tags: ['kubernetes', 'service-mesh', 'istio', 'linkerd', 'envoy', 'mtls', 'microservices'],
    isNew: true,
    featured: true,
    category: 'Kubernetes',
    createdAt: '2026-02-08',
  },
];

/**
 * Get all games
 */
export async function getAllGames(): Promise<Game[]> {
  return games;
}

/**
 * Get all active games (excluding coming soon)
 */
export async function getActiveGames(): Promise<Game[]> {
  return games.filter((game) => !game.isComingSoon);
}

/**
 * Get featured games (excluding coming soon)
 */
export async function getFeaturedGames(): Promise<Game[]> {
  return games.filter((game) => game.featured && !game.isComingSoon);
}

/**
 * Get a game by ID
 */
export async function getGameById(id: string): Promise<Game | undefined> {
  return games.find((game) => game.id === id);
}

/**
 * Get games by category
 */
export async function getGamesByCategory(category: string): Promise<Game[]> {
  return games.filter((game) => game.category?.toLowerCase() === category.toLowerCase());
}

/**
 * Get games by tag
 */
export async function getGamesByTag(tag: string): Promise<Game[]> {
  return games.filter((game) => game.tags.some((t) => t.toLowerCase() === tag.toLowerCase()));
}

/**
 * Get all game IDs (for static generation)
 */
export async function getAllGameIds(): Promise<string[]> {
  return games.filter((game) => !game.isComingSoon).map((game) => game.id);
}
